// we will create plugins

//in the scheam feature of Fastify we will define the schema for the request and response
// and we will use it to validate the request body
// and response body
// we will use fastify built in validation
// we will use fastify schema to validate request body

const createUserSchema = {
    body: {
        type: "object",
        required: ["username", "email", "password"],
        properties: {
            username: { type: "string", minLength: 3, maxLength: 30 },
            email: { type: "string", format: "email" },
            password: { type: "string", minLength: 6, maxLength: 100 },
        },
    },
    response: {
        201: {
            type: "object",
            properties: {
                "id": { type: "string" },
                // message: { type: "string" },
            },
        },
        400: {
            type: "object",
            properties: {
                error: { type: "string" },
                // message: { type: "string" },
            },
        },
    }
};

async function userRouter(fastify, opts) {

    fastify.post("/api/users", {schema: createUserSchema},async (request, reply) => {

        const{ username, email, password } = request.body;

        const userCollection = fastify.mongo.db.collection('users');
        const result= await userCollection.insertOne({
            username,
            email,
            password, 
        });

        console.log(result);
        fastify.log.info(`User created with id: ${result.insertedId}`);


        //validate request body
        // we do no tuse third part to validate request body
        // we will use fastify built in validation
        // we will use fastify schema to validate request body
        

        reply.code(201); // Set the response status code to 201 Created

        return {
            id: "12345", // This would typically be generated by your database
            name: "Ankit",
            message: "User created successfully",
        };
    });
}

export default userRouter;